runtime: python312

env_variables:
  SECRET_KEY: "researchforge-secret-2025"

entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
